packages:
  - packages/*
  - shared
  - tools/*

allowBuilds:
  '@parcel/watcher': true

catalog:
  typescript: 7.0.2
  vue: 3.5.43
  vite-plus: 1.1.0
  vite: npm:@voidzero-dev/vite-plus-core@1.1.0
  vite-plugin-monkey: 8.1.1
  '@vitejs/plugin-vue-jsx': 5.1.6
  sass-embedded: 1.105.1
  autoprefixer: 10.6.1
  postcss: 8.5.29
  gh-pages: 6.3.0
  '@types/node': 26.6.4
  '@types/crypto-js': 4.2.2
  crypto-js: 4.2.0
  viewerjs: 1.15.2
  '@inquirer/prompts': 8.7.3

minimumReleaseAgeExclude:
  - viewerjs@1.15.2

overrides:
  vite@*: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
