import { defineConfig } from 'vite-plus'
import { defineUserScriptConfig } from '@monkey/vite-userscript'

const matches = [
  '*://www.jianshu.com/go-wild*',
  '*://link.zhihu.com/*',
  '*://t.cn/*',
  '*://weibo.cn/sinaurl*',
  '*://mail.qq.com/cgi-bin/*',
  '*://wx.mail.qq.com/xmspamcheck/xmsafejump*',
  '*://c.pc.qq.com/middlem.html*',
  '*://c.pc.qq.com/middlect.html*',
  '*://c.pc.qq.com/pc.html*',
  '*://c.pc.qq.com/ios.html*',
  '*://c.pc.qq.com/android.html*',
  '*://app.yinxiang.com/OutboundRedirect.action*',
  '*://jump.bdimg.com/safecheck/*',
  '*://jump2.bdimg.com/safecheck/*',
  '*://link.csdn.net/*',
  '*://www.youtube.com/redirect*',
  '*://mp.weixin.qq.com/s/*',
  '*://mp.weixin.qq.com/mp/readtemplate*',
  '*://weixin110.qq.com/cgi-bin/mmspamsupport-bin/newredirectconfirmcgi*',
  '*://open.work.weixin.qq.com/wwopen/uriconfirm*',
  '*://developers.weixin.qq.com/community/middlepage/href*',
  '*://www.itdaan.com/link/*',
  '*://www.douban.com/link2/*',
  '*://www.360doc.com/content/*',
  '*://www.pixiv.net/jump.php*',
  '*://m.sogou.com/*/tc*',
  '*://m.sogou.com*/tc*',
  '*://www.chinaz.com/go.shtml*',
  '*://www.oschina.net/action/GoToLink*',
  '*://link.juejin.cn/*',
  '*://docs.qq.com/scenario/link.html*',
  '*://www.pc6.com/goread.html*',
  '*://afdian.net/link*',
  '*://afdian.com/link*',
  '*://ifdian.net/link*',
  '*://gitee.com/link*',
  '*://www.tianyancha.com/security*',
  '*://aiqicha.baidu.com/safetip*',
  '*://www.qcc.com/web/transfer-link*',
  '*://link.uisdc.com/*',
  '*://blog.51cto.com/transfer*',
  '*://leetcode.cn/link*',
  '*://huaban.com/go*',
  '*://security.feishu.cn/link/safety*',
  '*://redirect.epicgames.com/*',
  '*://steamcommunity.com/linkfilter/*',
  '*://*.yuque.com/r/goto*',
  '*://hd.nowcoder.com/link.html*',
  '*://game.bilibili.com/linkfilter/*',
  '*://www.bilibili.com/york/link-middle-page/pc*',
  '*://sspai.com/link*',
  '*://niu.sspai.com/link*',
  '*://jump.5ch.net/*',
  '*://www.kdocs.cn/office/link*',
  '*://shimo.im/outlink/black*',
  '*://google.urlshare.cn/umirror_url_check*',
  '*://www.coolapk.com/link*',
  '*://wpfx.org/go*',
  '*://cloud.tencent.com/developer/tools/blog-entry*',
  '*://support.qq.com/products/*/link-jump*',
  '*://txc.qq.com/products/*/link-jump*',
  '*://yq.aliyun.com/go/articleRenderRedirect*',
  '*://www.nodeseek.com/jump*',
  '*://www.yiqicha.com/thirdPage*',
  '*://www.iplaysoft.com/link*',
  '*://hellogithub.com/periodical/statistics/click*',
  '*://zmingcx.com/go.html*',
  '*://ref.gamer.com.tw/redir.php*',
  '*://ababtools.com/?plugin=redirect_page*',
  '*://help.aliyun.com/redirect*',
  '*://linux.do/*',
]

export default defineConfig(env =>
  defineUserScriptConfig(env, import.meta.url, {
    userscript: {
      name: 'redirect 外链跳转',
      description:
        '自动跳转(重定向)到目标链接，免去点击步骤。适配了简书、知乎、微博、QQ邮箱、QQPC、QQNT、印象笔记、贴吧、CSDN、YouTube、微信、企业微信、微信开放社区、开发者知识库、豆瓣、个人图书馆、Pixiv、搜狗、Google、站长之家、OSCHINA、掘金、腾讯文档、pc6下载站、爱发电、Gitee、天眼查、爱企查、企查查、优设网、51CTO、力扣、花瓣网、飞书、Epic、Steam、语雀、牛客网、哔哩哔哩、少数派、5ch、金山文档、石墨文档、urlshare、酷安、网盘分享、腾讯云开发者社区、腾讯兔小巢、云栖社区、NodeSeek、亿企查、异次元软件、HelloGitHub、知更鸟、巴哈姆特、ABABTOOLS、阿里云帮助中心、LINUX DO',
      author: 'sakura-flutter',
      namespace: 'https://github.com/sakura-flutter/tampermonkey-scripts',
      license: 'MIT',
      $extra: [
        ['compatible', 'chrome Latest'],
        ['compatible', 'firefox Latest'],
        ['compatible', 'edge Latest'],
      ],
      'run-at': 'document-start',
      match: matches,
      include: [/^https?:\/\/www\.google\..{2,7}url/],
    },
  }),
)
